services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000

    volumes:
      - C:\Users\suraj.kalloli\grafana\keycloak.ini:/etc/grafana/grafana.ini
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command:
      - start-dev
      - --import-realm
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak-config/:/opt/keycloak/data/import/

